const key ="productos_data"

let productos = JSON.parse(localStorage.getItem(key)) || [
    { id: 1, descuento: 37, stock : 43, nombre: "Hell is Us | Deluxe Edition (PC)", presentacion: "Steam Key - GLOBAL", categoria: "videojuegos", precio: 69.99, img: "/productosAssets/hell.jpeg", genero: "accion", descripcion: "Hell is Us es un juego de acción y aventuras en tercera persona centrado en el misterio y la exploración. El jugador toma el rol de Rémy, un soldado amnésico que regresa a su país de origen, Jadia, devastado por una guerra civil de 400 años."},
    { id: 2, descuento: 50, stock : 65, nombre: "Dying Light: The Beast (PC)", presentacion: "Steam Account - GLOBAL", categoria: "videojuegos", precio: 29.99, img: "/productosAssets/dying.jpg", genero: "accion", descripcion: "Dying Light es un videojuego de acción y supervivencia en primera persona ambientado en un mundo abierto postapocalíptico, donde los jugadores deben explorar una ciudad devastada por una epidemia para sobrevivir. Para ello, deben buscar suministros, fabricar armas y defenderse de hordas de zombis. El juego combina elementos de parkour y combate, con un ciclo de día y noche que cambia drásticamente el comportamiento de los enemigos."},
    { id: 3, descuento: 37, stock : 56, nombre: "RDO2 Juego PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/RDR2.jpg", genero: "accion", descripcion: "Red Dead Redemption 2 para PS4 es un juego de acción-aventura ambientado en el salvaje oeste en 1899, donde el jugador asume el papel de Arthur Morgan, un forajido de la banda de Van der Linde que lucha por sobrevivir mientras la era de los forajidos llega a su fin. El juego ofrece un mundo abierto detallado y con vida propia, una narrativa épica con dilemas morales, jugabilidad realista con combate, caza y exploración, y un modo multijugador online llamado Red Dead Online."},
    { id: 4, descuento: 37, stock : 3, nombre: "Hollow Knight PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/hollow.jpg", genero: "aventura", descripcion: "Hollow Knight es un videojuego de acción y aventura en 2D de tipo Metroidvania, ambientado en el reino subterráneo de insectos en ruinas Hallownest, donde el jugador controla a un misterioso caballero sin nombre que debe desentrañar los secretos del reino y combatir criaturas corrompidas. El juego destaca por su vasto mundo interconectado, controles 2D precisos, combate desafiante con habilidades evolutivas y la posibilidad de equipar reliquias llamadas amuletos, todo envuelto en un estilo artístico único."},
    { id: 5, descuento: 37, stock : 43, nombre: "Spiderman PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/spiderman.jpeg", genero: "aventura", descripcion: "Marvel's Spider-Man para PS4 es un videojuego de acción y aventuras en mundo abierto donde controlas a un experimentado Peter Parker como Spider-Man en una Nueva York original y vibrante. El juego destaca por su combate fluido e improvisado, acrobacias dinámicas, recorrido urbano ágil con telarañas, una historia original con personajes icónicos, y la capacidad de interactuar con el entorno para derrotar villanos."},
    { id: 6, descuento: 37, stock : 12, nombre: "Madden 25 PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/madden.jpeg", genero: "deporte", descripcion: "Madden NFL 25 para PS4 ofrece la experiencia de fútbol americano con modo Ultimate Team, modo Franquicia renovado conárboles de habilidades y modo Superestrella para la carrera de un jugador, además de la opción de jugar partidos rápidos. El juego cuenta con mecánicas de física mejoradas en el control del portador del balón y placajes, ofreciendo un mayor realismo y profundidad estratégica. También incluye presentación visual espectacular y funciones de accesibilidad, como la transcripción de chats online y recordatorios de controles."},
    { id: 7, descuento: 37, stock : 56, nombre: "2K25 PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/2k25.jpeg", genero: "deporte", descripcion: "NBA 2K25 para PS4 te permite vivir la experiencia del baloncesto profesional compitiendo en varios modos, como Mi CARRERA, donde creas tu jugador para dominar la liga, o MyTEAM, donde coleccionas cartas para formar el equipo de tus sueños. En La W, te conviertes en una estrella de la WNBA, mientras que Mi NBA te permite construir y dirigir tu propia dinastía. La versión de PS4 no incluye el modo La Ciudad/La Isla, característico de las plataformas de nueva generación, pero ofrece el Neighborhood para la experiencia de Mi CARRERA."},
    { id: 8, descuento: 37, stock : 45, nombre: "CALL OF DUTY BOIII PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/call.jpg", genero: "accion", descripcion: "Call of Duty: Black Ops III en PS4 es un shooter en primera persona con tres modos de juego: Campaña, Multijugador y Zombies. Ambientado en 2065, introduce un futuro distópico con supersoldados mejorados biotecnológicamente. Los jugadores experimentan combate moderno con mecánicas de parkour, correr por las paredes y un sistema de Especialistas con habilidades únicas."},
    { id: 9, descuento: 37, stock : 23, nombre: "SPIDERMAN MILES PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/miles.jpg", genero: "aventura", descripcion: "Marvel's Spider-Man: Miles Morales para PS4 es un videojuego de acción y aventura donde Miles Morales, tras el entrenamiento de Peter Parker, debe proteger Nueva York de una corporación y un ejército criminal mientras se convierte en su propia versión de Spider-Man. El juego explora su ascenso como héroe, su dominio de poderes como la bioelectricidad y el camuflaje, y su búsqueda de un sentido de pertenencia en su hogar de Brooklyn."},
    { id: 10, descuento: 37, stock : 65, nombre: "JUMP FORCE PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/jump.jpeg", genero: "lucha", descripcion: "Jump Force para PS4 es un videojuego de lucha en 3D, desarrollado por Spike Chunsoft y publicado por Bandai Namco, que reúne a héroes icónicos de diversas series de manga de la revista Weekly Shonen Jump para combatir una amenaza en el mundo real. Ofrece una jugabilidad en equipos de tres personajes, escenarios realistas y la opción de crear un avatar personalizado para competir en modos online y offline."},
    { id: 11, descuento: 37, stock : 87, nombre: "DEMON SLAYER PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/demon.jpg", genero: "lucha", descripcion: "Demon Slayer: Kimetsu no Yaiba - The Hinokami Chronicles para PS4 es un juego de lucha en 3D basado en la exitosa serie de anime, donde los jugadores reviven la historia de Tanjiro Kamado y sus esfuerzos para convertir a su hermana Nezuko de nuevo en humana, enfrentándose a demonios en emocionantes batallas. El juego permite a los jugadores experimentar el modo historia de la serie y participar en duelos 1 contra 1 o 2 contra 2, usando las habilidades de una lista de personajes que se expande."},
    { id: 12, descuento: 37, stock : 2, nombre: "2K26 PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/2k26.jpg", genero: "deporte", descripcion: "NBA 2K26 para PS4 se presenta como una entrega que busca revolucionar la experiencia de baloncesto virtual, incorporando la tecnología ProPLAY™ para animaciones más realistas y una jugabilidad mejorada."},
    { id: 13, descuento: 37, stock : 54, nombre: "CRONOS PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/cronos.jpg", genero: "accion", descripcion: "Cronos: The New Dawn es un juego de terror y supervivencia en tercera persona donde juegas como un Viajero que viaja al pasado (Polonia de los 80) desde un futuro postapocalíptico para detener una catástrofe. La trama gira en torno a una epidemia que transformó a la humanidad en monstruos, y tu misión es descubrir el origen del virus y evitar su propagación, enfrentándote a criaturas mutantes y gestionando recursos limitados en un mundo sombrío y retrofuturista."},
    { id: 14, descuento: 37, stock : 67, nombre: "CALL OF DUTY 7 PS4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/call7.jpg", genero: "accion", descripcion: "Call of Duty: Black Ops 7, que está ambientado en 2035, sigue a David Section Mason mientras lidera un equipo de élite contra un enemigo que busca desestabilizar el orden mundial utilizando el miedo como arma. El juego se basa en los pilares característicos de la serie, combinando una campaña cooperativa, un innovador multijugador con mapas futuristas y el modo Zombis por rondas en el Éter Oscuro."},
    { id: 15, descuento: 37, stock : 12, nombre: "BATTLEFIELD 6", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/battlefield.webp", genero: "accion", descripcion: "La sinopsis de Battlefield 6 (ahora conocido como Battlefield 2042) se desarrolla en un futuro cercano, en el año 2042, donde las principales naciones de la Tierra se han visto forzadas a depender de mercenarios y corporaciones militares privadas como la Pax Armata debido a la escasez de recursos y al cambio climático, lo que desestabiliza el orden mundial y empuja al mundo al borde de una guerra global."},
    { id: 16, descuento: 37, stock : 34, nombre: "BORDERLANDS 4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/borderlands.webp", genero: "accion", descripcion: "En Borderlands 4, eres uno de los cuatro nuevos Buscacámaras que aterrizan en el planeta Kairos, una tierra bajo el yugo del tiránico Guardián del Tiempo. Te unirás a la resistencia local para oponerte a su régimen opresivo, buscando la Bóveda del planeta y enfrentándote a monstruos, bandidos y bestias en un mundo lleno de exploración libre y combate caótico."},
    { id: 17, descuento: 37, stock : 12, nombre: "NINJA 4", presentacion: "digital", categoria: "videojuegos", precio: 199.00, img: "/productosAssets/ninja.jpg", genero: "accion", descripcion: "Un joven ninja prodigio llamado Yakumo se enfrenta al resurgimiento del Dragón Oscuro en un Tokio futurista y corrompido, mientras que el legendario Ryu Hayabusa también juega un papel importante"},
    { id: 20, descuento: 37, stock : 3, nombre: "PlayStation 5", presentacion: "digital", categoria: "consolas", precio: 199.00, img: "/productosAssets/ps5.jpeg", genero: "Hardware", descripcion: "La PlayStation 5 (PS5) es la quinta consola de sobremesa de Sony, destacando por su potencia de procesamiento AMD Zen 2 y GPU RDNA 2, un rápido SSD para tiempos de carga ultrarrápidos, y el revolucionario controlador DualSense con retroalimentación háptica y gatillos adaptativos para una inmersión sin precedentes. También ofrece audio 3D Tempest, retrocompatibilidad con juegos de PS4 y soporte para juegos exclusivos como Demon's Souls y Marvel's Spider-Man: Miles Morales."},
    { id: 21, descuento: 37, stock : 4, nombre: "Xbox Series X", presentacion: "digital", categoria: "consolas", precio: 199.00, img: "/productosAssets/xbox.webp", genero: "Hardware", descripcion: "La Xbox Series X es una consola potente y rápida de Microsoft, destacada por su SSD de 1 TB que reduce drásticamente los tiempos de carga, su capacidad para jugar a altas resoluciones y tasas de fotogramas de hasta 120 FPS, el sonido espacial 3D y el sistema Quick Resume que permite cambiar instantáneamente entre múltiples juegos. También incluye retrocompatibilidad con generaciones anteriores, diseño silencioso y eficiente, y la función Smart Delivery."},
]

let contador = productos.length;

const guardarEnLocalStorage=()=>{
    localStorage.setItem(key, JSON.stringify(productos));
}

const insert = (producto) => {
    producto.id = ++contador;
    productos.push(producto);
    guardarEnLocalStorage();
}

const get = () => productos;

const getProducto =(id)=>{
    return productos.find((prod)=>prod.id===id);
}

const deleteProducto =(id)=>{
    productos = productos.filter((prod)=>prod.id !== id);
    guardarEnLocalStorage();
}

const edit = (productoEditado) => {
    productos = productos.map((prod) =>
      prod.id === productoEditado.id ? productoEditado : prod
    );
    guardarEnLocalStorage();
  }


const productosApi = { insert, get,getProducto,deleteProducto,edit };
export default productosApi;


